### ISSUE TITLE
frogbot scan-pull-requests is scanning all the active pull requests but i wanted to scan only the based on the source branch and buildid is it possible to do that

### ISSUE THREAD

**Issue by nachammaichidambaram** [jfrog/frogbot#444]

**Comment by omerzi** [comment]
Hi @nachammaichidambaram, thank you for using Frogbot and reporting this issue. Regrettably, we are having a difficulty comprehending the complete situation due to a lack of context. Could I kindly ask you to fill out the [Bug Report](https://github.com/jfrog/frogbot/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) section with the full details of the issue you're experiencing? Thank you in advance.

**Comment by EyalDelarea** [comment]
This issue is being closed in favor of the following: https://github.com/jfrog/frogbot/issues/446.
