### ISSUE TITLE
Code Scan is not working for C# project 

### ISSUE THREAD

**Issue by svommina** [jfrog/frogbot#705]
I have followed the instruction given to set up repository scan of C# project, but it scan for nuget dependencies only not the exact code. I have written a small vulnerable code it has got spotted this code.   

Instructions followed from this page 
https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot/setup-frogbot/setup-frogbot-using-azure-pipelines

**Comment by eranturgeman** [comment]
Hello @svommina and thank you for using Frogbot!
Can you explain which scanner you expect yo see running but is not working?
Did you see them running on other projects? Do you have our advanced security package?

**Comment by eranturgeman** [comment]
@svommina 
Ok so couple of things:
1) Frogbot is not intended to be executed from within the CLI, but rather from within a CI. Let us check the command that is more suited to the CLI - 'jf audit'. You can run this command and see if the issues you are expecting to see are there (Frogbot itself is executing the exact same command and uses its output).
2) As for the JFrog advanced security package - this is our paid security package. In order to check if this package is available to you please contact you Jfrog representative and he/she can help you with that, I cannot see the your entitlement status without your customer details. If you are not entitled for this package, the results you are seeing make sense since our basic scan scans only packages.
3) As for the C# code you asked - Lets first check if you are entitled for the advanced security package so we will know what kinds of vulnerabilities your can insert, and that will be found by our scanners. If you are not entitled for JAS (Jfrog Advanced Security) you can try to insert any C# vulnerable package to your project and check the results. You can find a variety of known vulnerable dependencies here: https://nvd.nist.gov/vuln/search

**Comment by svommina** [comment]
@eranturgeman 

Thanks for explation and confirming to work with Frogbot we need Advanced Security Package.  In our installation we dont have this package.  I guess without this package jf audit also will not work right ?

**Comment by eranturgeman** [comment]
@svommina Not at all!
'jf audit' will work as well (Frogbot itself is calling 'jf audit' when scanning your project), but you will face the same results - if you are not entitled to Jfrog Advanced Security you cannot utilize them either in Frogbot nor in 'jf audit', but the basic scans will work for you in both of them.
Please feel free to Contact one of our representatives, they can explain better how the subscription to JAS works.
If you have any further question please feel free to contact us again :)
